const languages_text = {

    ro: {
        nav:["Acasa", "Galerie", "Despre noi", "Contact", "Licitatie"],
        homeHeroTitle: "Stejarul lui Avram Iancu",
        homeHeroSubTitle: "Liciteaza pentru ghinzile",
        homeHeroGreeting: "Bun venit,",
        featuresTitle: "Ce oferim?",
        features1Title: "Autenticitate",
        features1Text:"Ghinzi culese din stefarul autentic.",
        features2Title: "Incoltite",
        features2Text:"Incoltite cu grija in pamantul stramosesc.",
        features3Title: "Plante sanatoase",
        features3Text:"Plante care au crescut.",
        tourTitle:"Alaturet comunitatii noastre",
        tourText:"Creazati cont si alaturate comunitatii noastre, apoi incepe licitatia..",
        testimonialsTitle:"Ce spun membrii nostri",
        testimonials1Text:"„Când plantez o ghindă, simt că las un semn mic, dar plin de viață, pentru cei care vor veni după mine.”",
        testimonials1Name:"– Irina Dobre",
        testimonials2Text:"“În fiecare duminică ne adunăm, râdem, și punem mâna pe pământ. Așa cresc nu doar stejarii, ci și prieteniile dintre noi.”",
        testimonials2Name:"– Mihai Roșu",
        testimonials3Text:"“Voluntariatul ne-a învățat că adevărata răbdare nu e să aștepți ca ghinda să încolțească, ci să crezi că fiecare gest bun are rădăcini adânci.”",
        testimonials3Name:"– Lavinia Stoenescu",
        footer: "Ghindă cu Ghindă. All rights reserved.",
        galleryTitle:"Galerie Photo"
    },
    en: {
        nav: ["Home", "Gallery", "About Us", "Contact", "Auction"],
        homeHeroTitle: "Avram Iancu's oak",
        homeHeroSubTitle: "Bid for acorns",
        homeHeroGreeting: "Welcome,",
        featuresTitle: "What we offer?",
        features1Title: "Authenticity",
        features1Text: "Acorns collected from the authentic oak.",
        features2Title: "Sprouted",
        features2Text: "Carefully sprouted in ancestral soil.",
        features3Title: "Healthy plants",
        features3Text: "Plants that have grown.",
        tourTitle: "Join our community",
        tourText: "Create an account and join our community, then start bidding.",
        testimonialsTitle: "What our members say",
        testimonials1Text: "“When I plant an acorn, I feel like I'm leaving a small but living mark for those who will come after me.”",
        testimonials1Name: "– Irina Dobre",
        testimonials2Text: "“Every Sunday we gather, laugh, and put our hands in the soil. That’s how not only oaks grow, but also the friendships between us.”",
        testimonials2Name: "– Mihai Roșu",
        testimonials3Text: "“Volunteering has taught us that true patience is not waiting for the acorn to sprout, but believing that every good gesture has deep roots.”",
        testimonials3Name: "– Lavinia Stoenescu",
        footer: "Acorn by Acorn. All rights reserved.",
        galleryTitle:"Photo Gallery"
    },
    de: {
        nav: ["Startseite", "Galerie", "Über uns", "Kontakt", "Auktion"],
        homeHeroTitle: "Avram Iancus Eiche",
        homeHeroSubTitle: "Bieten Sie auf Eicheln",
        homeHeroGreeting: "Willkommen,",
        featuresTitle: "Was bieten wir an?",
        features1Title: "Authentizität",
        features1Text: "Eicheln, die von der ursprünglichen Eiche gesammelt wurden.",
        features2Title: "Gekeimt",
        features2Text: "Sorgfältig im angestammten Boden gekeimt.",
        features3Title: "Gesunde Pflanzen",
        features3Text: "Pflanzen, die gewachsen sind.",
        tourTitle: "Treten Sie unserer Gemeinschaft bei",
        tourText: "Erstellen Sie ein Konto und werden Sie Teil unserer Gemeinschaft, dann beginnen Sie mit dem Bieten.",
        testimonialsTitle: "Was unsere Mitglieder sagen",
        testimonials1Text: "„Wenn ich eine Eichel pflanze, habe ich das Gefühl, eine kleine, aber lebendige Spur für diejenigen zu hinterlassen, die nach mir kommen werden.“",
        testimonials1Name: "– Irina Dobre",
        testimonials2Text: "„Jeden Sonntag treffen wir uns, lachen und arbeiten mit unseren Händen in der Erde. So wachsen nicht nur die Eichen, sondern auch die Freundschaften zwischen uns.“",
        testimonials2Name: "– Mihai Roșu",
        testimonials3Text: "„Das Ehrenamt hat uns gelehrt, dass wahre Geduld nicht darin besteht zu warten, bis die Eichel keimt, sondern daran zu glauben, dass jede gute Tat tiefe Wurzeln hat.“",
        testimonials3Name: "– Lavinia Stoenescu",
        footer: "Eichel für Eichel. Alle Rechte vorbehalten.",
        galleryTitle:"Galerie Photo"
    },
}

export default languages_text